# coding: utf-8

"""
    Thola

    REST API for Thola.  For more information look at our Github : https://github.com/inexio/thola  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import thola_client
from thola_client.models.read_server_request import ReadServerRequest  # noqa: E501
from thola_client.rest import ApiException


class TestReadServerRequest(unittest.TestCase):
    """ReadServerRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReadServerRequest(self):
        """Test ReadServerRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = thola_client.models.read_server_request.ReadServerRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
