# coding: utf-8

"""
    Thola

    REST API for Thola.  For more information look at our Github : https://github.com/inexio/thola  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import thola_client
from thola_client.models.read_memory_usage_request import ReadMemoryUsageRequest  # noqa: E501
from thola_client.rest import ApiException


class TestReadMemoryUsageRequest(unittest.TestCase):
    """ReadMemoryUsageRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReadMemoryUsageRequest(self):
        """Test ReadMemoryUsageRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = thola_client.models.read_memory_usage_request.ReadMemoryUsageRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
