# coding: utf-8

"""
    Thola

    REST API for Thola.  For more information look at our Github : https://github.com/inexio/thola  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import thola_client
from thola_client.api.read_api import ReadApi  # noqa: E501
from thola_client.rest import ApiException


class TestReadApi(unittest.TestCase):
    """ReadApi unit test stubs"""

    def setUp(self):
        self.api = thola_client.api.read_api.ReadApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_hardware_health(self):
        """Test case for hardware_health

        Reads out hardware health data of a device.  # noqa: E501
        """
        pass

    def test_read_available_components(self):
        """Test case for read_available_components

        Returns the available components for the device.  # noqa: E501
        """
        pass

    def test_read_count_interfaces(self):
        """Test case for read_count_interfaces

        Counts the interfaces of a device.  # noqa: E501
        """
        pass

    def test_read_cpu_load(self):
        """Test case for read_cpu_load

        Read out the CPU load of a device.  # noqa: E501
        """
        pass

    def test_read_disk(self):
        """Test case for read_disk

        Reads out disk data of a device.  # noqa: E501
        """
        pass

    def test_read_interfaces(self):
        """Test case for read_interfaces

        Reads out data of the interfaces of a device.  # noqa: E501
        """
        pass

    def test_read_memory_usage(self):
        """Test case for read_memory_usage

        Read out the memory usage of a device.  # noqa: E501
        """
        pass

    def test_read_sbc(self):
        """Test case for read_sbc

        Reads out SBC data of a device.  # noqa: E501
        """
        pass

    def test_read_server(self):
        """Test case for read_server

        Reads out server data of a device.  # noqa: E501
        """
        pass

    def test_read_ups(self):
        """Test case for read_ups

        Reads out UPS data of a device.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
