# coding: utf-8

"""
    Thola

    REST API for Thola.  For more information look at our Github : https://github.com/inexio/thola  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import thola_client
from thola_client.api.check_api import CheckApi  # noqa: E501
from thola_client.rest import ApiException


class TestCheckApi(unittest.TestCase):
    """CheckApi unit test stubs"""

    def setUp(self):
        self.api = thola_client.api.check_api.CheckApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_check_cpu_load(self):
        """Test case for check_cpu_load

        Check the cpu load of a device.  # noqa: E501
        """
        pass

    def test_check_disk(self):
        """Test case for check_disk

        Check the disk of a device.  # noqa: E501
        """
        pass

    def test_check_hardware_health(self):
        """Test case for check_hardware_health

        Check an hardware health of an device.  # noqa: E501
        """
        pass

    def test_check_identify(self):
        """Test case for check_identify

        Checks if identify matches the expectations.  # noqa: E501
        """
        pass

    def test_check_interface_metrics(self):
        """Test case for check_interface_metrics

        Check to read out interface metrics.  # noqa: E501
        """
        pass

    def test_check_memory_usage(self):
        """Test case for check_memory_usage

        Check the memory usage of a device.  # noqa: E501
        """
        pass

    def test_check_sbc(self):
        """Test case for check_sbc

        Check an sbc device.  # noqa: E501
        """
        pass

    def test_check_server(self):
        """Test case for check_server

        Check a linux server.  # noqa: E501
        """
        pass

    def test_check_snmp(self):
        """Test case for check_snmp

        Checks SNMP availability.  # noqa: E501
        """
        pass

    def test_check_thola_server(self):
        """Test case for check_thola_server

        Check existence of thola servers.  # noqa: E501
        """
        pass

    def test_check_ups(self):
        """Test case for check_ups

        Checks whether a UPS device has its main voltage applied.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
