# coding: utf-8

"""
    Thola

    REST API for Thola.  For more information look at our Github : https://github.com/inexio/thola  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from thola_client.configuration import Configuration


class CheckUPSRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'battery_current_thresholds': 'Thresholds',
        'battery_temperature_thresholds': 'Thresholds',
        'current_load_thresholds': 'Thresholds',
        'device_data': 'DeviceData',
        'json_metrics': 'bool',
        'print_performance_data': 'bool',
        'rectifier_current_thresholds': 'Thresholds',
        'system_voltage_thresholds': 'Thresholds',
        'timeout': 'int'
    }

    attribute_map = {
        'battery_current_thresholds': 'batteryCurrentThresholds',
        'battery_temperature_thresholds': 'batteryTemperatureThresholds',
        'current_load_thresholds': 'currentLoadThresholds',
        'device_data': 'device_data',
        'json_metrics': 'json_metrics',
        'print_performance_data': 'print_performance_data',
        'rectifier_current_thresholds': 'rectifierCurrentThresholds',
        'system_voltage_thresholds': 'systemVoltageThresholds',
        'timeout': 'timeout'
    }

    def __init__(self, battery_current_thresholds=None, battery_temperature_thresholds=None, current_load_thresholds=None, device_data=None, json_metrics=None, print_performance_data=None, rectifier_current_thresholds=None, system_voltage_thresholds=None, timeout=None, _configuration=None):  # noqa: E501
        """CheckUPSRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._battery_current_thresholds = None
        self._battery_temperature_thresholds = None
        self._current_load_thresholds = None
        self._device_data = None
        self._json_metrics = None
        self._print_performance_data = None
        self._rectifier_current_thresholds = None
        self._system_voltage_thresholds = None
        self._timeout = None
        self.discriminator = None

        if battery_current_thresholds is not None:
            self.battery_current_thresholds = battery_current_thresholds
        if battery_temperature_thresholds is not None:
            self.battery_temperature_thresholds = battery_temperature_thresholds
        if current_load_thresholds is not None:
            self.current_load_thresholds = current_load_thresholds
        if device_data is not None:
            self.device_data = device_data
        if json_metrics is not None:
            self.json_metrics = json_metrics
        if print_performance_data is not None:
            self.print_performance_data = print_performance_data
        if rectifier_current_thresholds is not None:
            self.rectifier_current_thresholds = rectifier_current_thresholds
        if system_voltage_thresholds is not None:
            self.system_voltage_thresholds = system_voltage_thresholds
        if timeout is not None:
            self.timeout = timeout

    @property
    def battery_current_thresholds(self):
        """Gets the battery_current_thresholds of this CheckUPSRequest.  # noqa: E501


        :return: The battery_current_thresholds of this CheckUPSRequest.  # noqa: E501
        :rtype: Thresholds
        """
        return self._battery_current_thresholds

    @battery_current_thresholds.setter
    def battery_current_thresholds(self, battery_current_thresholds):
        """Sets the battery_current_thresholds of this CheckUPSRequest.


        :param battery_current_thresholds: The battery_current_thresholds of this CheckUPSRequest.  # noqa: E501
        :type: Thresholds
        """

        self._battery_current_thresholds = battery_current_thresholds

    @property
    def battery_temperature_thresholds(self):
        """Gets the battery_temperature_thresholds of this CheckUPSRequest.  # noqa: E501


        :return: The battery_temperature_thresholds of this CheckUPSRequest.  # noqa: E501
        :rtype: Thresholds
        """
        return self._battery_temperature_thresholds

    @battery_temperature_thresholds.setter
    def battery_temperature_thresholds(self, battery_temperature_thresholds):
        """Sets the battery_temperature_thresholds of this CheckUPSRequest.


        :param battery_temperature_thresholds: The battery_temperature_thresholds of this CheckUPSRequest.  # noqa: E501
        :type: Thresholds
        """

        self._battery_temperature_thresholds = battery_temperature_thresholds

    @property
    def current_load_thresholds(self):
        """Gets the current_load_thresholds of this CheckUPSRequest.  # noqa: E501


        :return: The current_load_thresholds of this CheckUPSRequest.  # noqa: E501
        :rtype: Thresholds
        """
        return self._current_load_thresholds

    @current_load_thresholds.setter
    def current_load_thresholds(self, current_load_thresholds):
        """Sets the current_load_thresholds of this CheckUPSRequest.


        :param current_load_thresholds: The current_load_thresholds of this CheckUPSRequest.  # noqa: E501
        :type: Thresholds
        """

        self._current_load_thresholds = current_load_thresholds

    @property
    def device_data(self):
        """Gets the device_data of this CheckUPSRequest.  # noqa: E501


        :return: The device_data of this CheckUPSRequest.  # noqa: E501
        :rtype: DeviceData
        """
        return self._device_data

    @device_data.setter
    def device_data(self, device_data):
        """Sets the device_data of this CheckUPSRequest.


        :param device_data: The device_data of this CheckUPSRequest.  # noqa: E501
        :type: DeviceData
        """

        self._device_data = device_data

    @property
    def json_metrics(self):
        """Gets the json_metrics of this CheckUPSRequest.  # noqa: E501


        :return: The json_metrics of this CheckUPSRequest.  # noqa: E501
        :rtype: bool
        """
        return self._json_metrics

    @json_metrics.setter
    def json_metrics(self, json_metrics):
        """Sets the json_metrics of this CheckUPSRequest.


        :param json_metrics: The json_metrics of this CheckUPSRequest.  # noqa: E501
        :type: bool
        """

        self._json_metrics = json_metrics

    @property
    def print_performance_data(self):
        """Gets the print_performance_data of this CheckUPSRequest.  # noqa: E501


        :return: The print_performance_data of this CheckUPSRequest.  # noqa: E501
        :rtype: bool
        """
        return self._print_performance_data

    @print_performance_data.setter
    def print_performance_data(self, print_performance_data):
        """Sets the print_performance_data of this CheckUPSRequest.


        :param print_performance_data: The print_performance_data of this CheckUPSRequest.  # noqa: E501
        :type: bool
        """

        self._print_performance_data = print_performance_data

    @property
    def rectifier_current_thresholds(self):
        """Gets the rectifier_current_thresholds of this CheckUPSRequest.  # noqa: E501


        :return: The rectifier_current_thresholds of this CheckUPSRequest.  # noqa: E501
        :rtype: Thresholds
        """
        return self._rectifier_current_thresholds

    @rectifier_current_thresholds.setter
    def rectifier_current_thresholds(self, rectifier_current_thresholds):
        """Sets the rectifier_current_thresholds of this CheckUPSRequest.


        :param rectifier_current_thresholds: The rectifier_current_thresholds of this CheckUPSRequest.  # noqa: E501
        :type: Thresholds
        """

        self._rectifier_current_thresholds = rectifier_current_thresholds

    @property
    def system_voltage_thresholds(self):
        """Gets the system_voltage_thresholds of this CheckUPSRequest.  # noqa: E501


        :return: The system_voltage_thresholds of this CheckUPSRequest.  # noqa: E501
        :rtype: Thresholds
        """
        return self._system_voltage_thresholds

    @system_voltage_thresholds.setter
    def system_voltage_thresholds(self, system_voltage_thresholds):
        """Sets the system_voltage_thresholds of this CheckUPSRequest.


        :param system_voltage_thresholds: The system_voltage_thresholds of this CheckUPSRequest.  # noqa: E501
        :type: Thresholds
        """

        self._system_voltage_thresholds = system_voltage_thresholds

    @property
    def timeout(self):
        """Gets the timeout of this CheckUPSRequest.  # noqa: E501

        Timeout for the request (0 => no timeout)  # noqa: E501

        :return: The timeout of this CheckUPSRequest.  # noqa: E501
        :rtype: int
        """
        return self._timeout

    @timeout.setter
    def timeout(self, timeout):
        """Sets the timeout of this CheckUPSRequest.

        Timeout for the request (0 => no timeout)  # noqa: E501

        :param timeout: The timeout of this CheckUPSRequest.  # noqa: E501
        :type: int
        """

        self._timeout = timeout

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CheckUPSRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CheckUPSRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CheckUPSRequest):
            return True

        return self.to_dict() != other.to_dict()
