# coding: utf-8

"""
    Thola

    REST API for Thola.  For more information look at our Github : https://github.com/inexio/thola  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from thola_client.configuration import Configuration


class CheckTholaServerRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'json_metrics': 'bool',
        'print_performance_data': 'bool',
        'timeout': 'int'
    }

    attribute_map = {
        'json_metrics': 'json_metrics',
        'print_performance_data': 'print_performance_data',
        'timeout': 'timeout'
    }

    def __init__(self, json_metrics=None, print_performance_data=None, timeout=None, _configuration=None):  # noqa: E501
        """CheckTholaServerRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._json_metrics = None
        self._print_performance_data = None
        self._timeout = None
        self.discriminator = None

        if json_metrics is not None:
            self.json_metrics = json_metrics
        if print_performance_data is not None:
            self.print_performance_data = print_performance_data
        if timeout is not None:
            self.timeout = timeout

    @property
    def json_metrics(self):
        """Gets the json_metrics of this CheckTholaServerRequest.  # noqa: E501


        :return: The json_metrics of this CheckTholaServerRequest.  # noqa: E501
        :rtype: bool
        """
        return self._json_metrics

    @json_metrics.setter
    def json_metrics(self, json_metrics):
        """Sets the json_metrics of this CheckTholaServerRequest.


        :param json_metrics: The json_metrics of this CheckTholaServerRequest.  # noqa: E501
        :type: bool
        """

        self._json_metrics = json_metrics

    @property
    def print_performance_data(self):
        """Gets the print_performance_data of this CheckTholaServerRequest.  # noqa: E501


        :return: The print_performance_data of this CheckTholaServerRequest.  # noqa: E501
        :rtype: bool
        """
        return self._print_performance_data

    @print_performance_data.setter
    def print_performance_data(self, print_performance_data):
        """Sets the print_performance_data of this CheckTholaServerRequest.


        :param print_performance_data: The print_performance_data of this CheckTholaServerRequest.  # noqa: E501
        :type: bool
        """

        self._print_performance_data = print_performance_data

    @property
    def timeout(self):
        """Gets the timeout of this CheckTholaServerRequest.  # noqa: E501


        :return: The timeout of this CheckTholaServerRequest.  # noqa: E501
        :rtype: int
        """
        return self._timeout

    @timeout.setter
    def timeout(self, timeout):
        """Sets the timeout of this CheckTholaServerRequest.


        :param timeout: The timeout of this CheckTholaServerRequest.  # noqa: E501
        :type: int
        """

        self._timeout = timeout

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CheckTholaServerRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CheckTholaServerRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CheckTholaServerRequest):
            return True

        return self.to_dict() != other.to_dict()
