# coding: utf-8

"""
    Thola

    REST API for Thola.  For more information look at our Github : https://github.com/inexio/thola  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from thola_client.configuration import Configuration


class CheckIdentifyRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'device_data': 'DeviceData',
        'expectations': 'Device',
        'json_metrics': 'bool',
        'model_diff_warning': 'bool',
        'model_series_diff_warning': 'bool',
        'os_diff_warning': 'bool',
        'os_version_diff_warning': 'bool',
        'print_performance_data': 'bool',
        'serial_number_diff_warning': 'bool',
        'timeout': 'int',
        'vendor_diff_warning': 'bool'
    }

    attribute_map = {
        'device_data': 'device_data',
        'expectations': 'expectations',
        'json_metrics': 'json_metrics',
        'model_diff_warning': 'model_diff_warning',
        'model_series_diff_warning': 'model_series_diff_warning',
        'os_diff_warning': 'os_diff_warning',
        'os_version_diff_warning': 'os_version_diff_warning',
        'print_performance_data': 'print_performance_data',
        'serial_number_diff_warning': 'serial_number_diff_warning',
        'timeout': 'timeout',
        'vendor_diff_warning': 'vendor_diff_warning'
    }

    def __init__(self, device_data=None, expectations=None, json_metrics=None, model_diff_warning=None, model_series_diff_warning=None, os_diff_warning=None, os_version_diff_warning=None, print_performance_data=None, serial_number_diff_warning=None, timeout=None, vendor_diff_warning=None, _configuration=None):  # noqa: E501
        """CheckIdentifyRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._device_data = None
        self._expectations = None
        self._json_metrics = None
        self._model_diff_warning = None
        self._model_series_diff_warning = None
        self._os_diff_warning = None
        self._os_version_diff_warning = None
        self._print_performance_data = None
        self._serial_number_diff_warning = None
        self._timeout = None
        self._vendor_diff_warning = None
        self.discriminator = None

        if device_data is not None:
            self.device_data = device_data
        if expectations is not None:
            self.expectations = expectations
        if json_metrics is not None:
            self.json_metrics = json_metrics
        if model_diff_warning is not None:
            self.model_diff_warning = model_diff_warning
        if model_series_diff_warning is not None:
            self.model_series_diff_warning = model_series_diff_warning
        if os_diff_warning is not None:
            self.os_diff_warning = os_diff_warning
        if os_version_diff_warning is not None:
            self.os_version_diff_warning = os_version_diff_warning
        if print_performance_data is not None:
            self.print_performance_data = print_performance_data
        if serial_number_diff_warning is not None:
            self.serial_number_diff_warning = serial_number_diff_warning
        if timeout is not None:
            self.timeout = timeout
        if vendor_diff_warning is not None:
            self.vendor_diff_warning = vendor_diff_warning

    @property
    def device_data(self):
        """Gets the device_data of this CheckIdentifyRequest.  # noqa: E501


        :return: The device_data of this CheckIdentifyRequest.  # noqa: E501
        :rtype: DeviceData
        """
        return self._device_data

    @device_data.setter
    def device_data(self, device_data):
        """Sets the device_data of this CheckIdentifyRequest.


        :param device_data: The device_data of this CheckIdentifyRequest.  # noqa: E501
        :type: DeviceData
        """

        self._device_data = device_data

    @property
    def expectations(self):
        """Gets the expectations of this CheckIdentifyRequest.  # noqa: E501


        :return: The expectations of this CheckIdentifyRequest.  # noqa: E501
        :rtype: Device
        """
        return self._expectations

    @expectations.setter
    def expectations(self, expectations):
        """Sets the expectations of this CheckIdentifyRequest.


        :param expectations: The expectations of this CheckIdentifyRequest.  # noqa: E501
        :type: Device
        """

        self._expectations = expectations

    @property
    def json_metrics(self):
        """Gets the json_metrics of this CheckIdentifyRequest.  # noqa: E501


        :return: The json_metrics of this CheckIdentifyRequest.  # noqa: E501
        :rtype: bool
        """
        return self._json_metrics

    @json_metrics.setter
    def json_metrics(self, json_metrics):
        """Sets the json_metrics of this CheckIdentifyRequest.


        :param json_metrics: The json_metrics of this CheckIdentifyRequest.  # noqa: E501
        :type: bool
        """

        self._json_metrics = json_metrics

    @property
    def model_diff_warning(self):
        """Gets the model_diff_warning of this CheckIdentifyRequest.  # noqa: E501


        :return: The model_diff_warning of this CheckIdentifyRequest.  # noqa: E501
        :rtype: bool
        """
        return self._model_diff_warning

    @model_diff_warning.setter
    def model_diff_warning(self, model_diff_warning):
        """Sets the model_diff_warning of this CheckIdentifyRequest.


        :param model_diff_warning: The model_diff_warning of this CheckIdentifyRequest.  # noqa: E501
        :type: bool
        """

        self._model_diff_warning = model_diff_warning

    @property
    def model_series_diff_warning(self):
        """Gets the model_series_diff_warning of this CheckIdentifyRequest.  # noqa: E501


        :return: The model_series_diff_warning of this CheckIdentifyRequest.  # noqa: E501
        :rtype: bool
        """
        return self._model_series_diff_warning

    @model_series_diff_warning.setter
    def model_series_diff_warning(self, model_series_diff_warning):
        """Sets the model_series_diff_warning of this CheckIdentifyRequest.


        :param model_series_diff_warning: The model_series_diff_warning of this CheckIdentifyRequest.  # noqa: E501
        :type: bool
        """

        self._model_series_diff_warning = model_series_diff_warning

    @property
    def os_diff_warning(self):
        """Gets the os_diff_warning of this CheckIdentifyRequest.  # noqa: E501


        :return: The os_diff_warning of this CheckIdentifyRequest.  # noqa: E501
        :rtype: bool
        """
        return self._os_diff_warning

    @os_diff_warning.setter
    def os_diff_warning(self, os_diff_warning):
        """Sets the os_diff_warning of this CheckIdentifyRequest.


        :param os_diff_warning: The os_diff_warning of this CheckIdentifyRequest.  # noqa: E501
        :type: bool
        """

        self._os_diff_warning = os_diff_warning

    @property
    def os_version_diff_warning(self):
        """Gets the os_version_diff_warning of this CheckIdentifyRequest.  # noqa: E501


        :return: The os_version_diff_warning of this CheckIdentifyRequest.  # noqa: E501
        :rtype: bool
        """
        return self._os_version_diff_warning

    @os_version_diff_warning.setter
    def os_version_diff_warning(self, os_version_diff_warning):
        """Sets the os_version_diff_warning of this CheckIdentifyRequest.


        :param os_version_diff_warning: The os_version_diff_warning of this CheckIdentifyRequest.  # noqa: E501
        :type: bool
        """

        self._os_version_diff_warning = os_version_diff_warning

    @property
    def print_performance_data(self):
        """Gets the print_performance_data of this CheckIdentifyRequest.  # noqa: E501


        :return: The print_performance_data of this CheckIdentifyRequest.  # noqa: E501
        :rtype: bool
        """
        return self._print_performance_data

    @print_performance_data.setter
    def print_performance_data(self, print_performance_data):
        """Sets the print_performance_data of this CheckIdentifyRequest.


        :param print_performance_data: The print_performance_data of this CheckIdentifyRequest.  # noqa: E501
        :type: bool
        """

        self._print_performance_data = print_performance_data

    @property
    def serial_number_diff_warning(self):
        """Gets the serial_number_diff_warning of this CheckIdentifyRequest.  # noqa: E501


        :return: The serial_number_diff_warning of this CheckIdentifyRequest.  # noqa: E501
        :rtype: bool
        """
        return self._serial_number_diff_warning

    @serial_number_diff_warning.setter
    def serial_number_diff_warning(self, serial_number_diff_warning):
        """Sets the serial_number_diff_warning of this CheckIdentifyRequest.


        :param serial_number_diff_warning: The serial_number_diff_warning of this CheckIdentifyRequest.  # noqa: E501
        :type: bool
        """

        self._serial_number_diff_warning = serial_number_diff_warning

    @property
    def timeout(self):
        """Gets the timeout of this CheckIdentifyRequest.  # noqa: E501

        Timeout for the request (0 => no timeout)  # noqa: E501

        :return: The timeout of this CheckIdentifyRequest.  # noqa: E501
        :rtype: int
        """
        return self._timeout

    @timeout.setter
    def timeout(self, timeout):
        """Sets the timeout of this CheckIdentifyRequest.

        Timeout for the request (0 => no timeout)  # noqa: E501

        :param timeout: The timeout of this CheckIdentifyRequest.  # noqa: E501
        :type: int
        """

        self._timeout = timeout

    @property
    def vendor_diff_warning(self):
        """Gets the vendor_diff_warning of this CheckIdentifyRequest.  # noqa: E501


        :return: The vendor_diff_warning of this CheckIdentifyRequest.  # noqa: E501
        :rtype: bool
        """
        return self._vendor_diff_warning

    @vendor_diff_warning.setter
    def vendor_diff_warning(self, vendor_diff_warning):
        """Sets the vendor_diff_warning of this CheckIdentifyRequest.


        :param vendor_diff_warning: The vendor_diff_warning of this CheckIdentifyRequest.  # noqa: E501
        :type: bool
        """

        self._vendor_diff_warning = vendor_diff_warning

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CheckIdentifyRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CheckIdentifyRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CheckIdentifyRequest):
            return True

        return self.to_dict() != other.to_dict()
