# coding: utf-8

"""
    Thola

    REST API for Thola.  For more information look at our Github : https://github.com/inexio/thola  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from thola_client.configuration import Configuration


class ConnectionData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'http': 'HTTPConnectionData',
        'snmp': 'SNMPConnectionData'
    }

    attribute_map = {
        'http': 'http',
        'snmp': 'snmp'
    }

    def __init__(self, http=None, snmp=None, _configuration=None):  # noqa: E501
        """ConnectionData - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._http = None
        self._snmp = None
        self.discriminator = None

        if http is not None:
            self.http = http
        if snmp is not None:
            self.snmp = snmp

    @property
    def http(self):
        """Gets the http of this ConnectionData.  # noqa: E501


        :return: The http of this ConnectionData.  # noqa: E501
        :rtype: HTTPConnectionData
        """
        return self._http

    @http.setter
    def http(self, http):
        """Sets the http of this ConnectionData.


        :param http: The http of this ConnectionData.  # noqa: E501
        :type: HTTPConnectionData
        """

        self._http = http

    @property
    def snmp(self):
        """Gets the snmp of this ConnectionData.  # noqa: E501


        :return: The snmp of this ConnectionData.  # noqa: E501
        :rtype: SNMPConnectionData
        """
        return self._snmp

    @snmp.setter
    def snmp(self, snmp):
        """Sets the snmp of this ConnectionData.


        :param snmp: The snmp of this ConnectionData.  # noqa: E501
        :type: SNMPConnectionData
        """

        self._snmp = snmp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConnectionData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConnectionData):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ConnectionData):
            return True

        return self.to_dict() != other.to_dict()
