# coding: utf-8

"""
    Thola

    REST API for Thola.  For more information look at our Github : https://github.com/inexio/thola  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from thola_client.configuration import Configuration


class CPUComponent(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'load': 'list[float]',
        'temperature': 'list[float]'
    }

    attribute_map = {
        'load': 'load',
        'temperature': 'temperature'
    }

    def __init__(self, load=None, temperature=None, _configuration=None):  # noqa: E501
        """CPUComponent - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._load = None
        self._temperature = None
        self.discriminator = None

        if load is not None:
            self.load = load
        if temperature is not None:
            self.temperature = temperature

    @property
    def load(self):
        """Gets the load of this CPUComponent.  # noqa: E501


        :return: The load of this CPUComponent.  # noqa: E501
        :rtype: list[float]
        """
        return self._load

    @load.setter
    def load(self, load):
        """Sets the load of this CPUComponent.


        :param load: The load of this CPUComponent.  # noqa: E501
        :type: list[float]
        """

        self._load = load

    @property
    def temperature(self):
        """Gets the temperature of this CPUComponent.  # noqa: E501


        :return: The temperature of this CPUComponent.  # noqa: E501
        :rtype: list[float]
        """
        return self._temperature

    @temperature.setter
    def temperature(self, temperature):
        """Sets the temperature of this CPUComponent.


        :param temperature: The temperature of this CPUComponent.  # noqa: E501
        :type: list[float]
        """

        self._temperature = temperature

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CPUComponent, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CPUComponent):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CPUComponent):
            return True

        return self.to_dict() != other.to_dict()
