# coding: utf-8

"""
    Thola

    REST API for Thola.  For more information look at our Github : https://github.com/inexio/thola  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from thola_client.configuration import Configuration


class PerformanceDataPoint(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'label': 'str',
        'max': 'object',
        'metric': 'str',
        'min': 'object',
        'thresholds': 'Thresholds',
        'unit': 'str',
        'value': 'object'
    }

    attribute_map = {
        'label': 'label',
        'max': 'max',
        'metric': 'metric',
        'min': 'min',
        'thresholds': 'thresholds',
        'unit': 'unit',
        'value': 'value'
    }

    def __init__(self, label=None, max=None, metric=None, min=None, thresholds=None, unit=None, value=None, _configuration=None):  # noqa: E501
        """PerformanceDataPoint - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._label = None
        self._max = None
        self._metric = None
        self._min = None
        self._thresholds = None
        self._unit = None
        self._value = None
        self.discriminator = None

        if label is not None:
            self.label = label
        if max is not None:
            self.max = max
        if metric is not None:
            self.metric = metric
        if min is not None:
            self.min = min
        if thresholds is not None:
            self.thresholds = thresholds
        if unit is not None:
            self.unit = unit
        if value is not None:
            self.value = value

    @property
    def label(self):
        """Gets the label of this PerformanceDataPoint.  # noqa: E501


        :return: The label of this PerformanceDataPoint.  # noqa: E501
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this PerformanceDataPoint.


        :param label: The label of this PerformanceDataPoint.  # noqa: E501
        :type: str
        """

        self._label = label

    @property
    def max(self):
        """Gets the max of this PerformanceDataPoint.  # noqa: E501


        :return: The max of this PerformanceDataPoint.  # noqa: E501
        :rtype: object
        """
        return self._max

    @max.setter
    def max(self, max):
        """Sets the max of this PerformanceDataPoint.


        :param max: The max of this PerformanceDataPoint.  # noqa: E501
        :type: object
        """

        self._max = max

    @property
    def metric(self):
        """Gets the metric of this PerformanceDataPoint.  # noqa: E501


        :return: The metric of this PerformanceDataPoint.  # noqa: E501
        :rtype: str
        """
        return self._metric

    @metric.setter
    def metric(self, metric):
        """Sets the metric of this PerformanceDataPoint.


        :param metric: The metric of this PerformanceDataPoint.  # noqa: E501
        :type: str
        """

        self._metric = metric

    @property
    def min(self):
        """Gets the min of this PerformanceDataPoint.  # noqa: E501


        :return: The min of this PerformanceDataPoint.  # noqa: E501
        :rtype: object
        """
        return self._min

    @min.setter
    def min(self, min):
        """Sets the min of this PerformanceDataPoint.


        :param min: The min of this PerformanceDataPoint.  # noqa: E501
        :type: object
        """

        self._min = min

    @property
    def thresholds(self):
        """Gets the thresholds of this PerformanceDataPoint.  # noqa: E501


        :return: The thresholds of this PerformanceDataPoint.  # noqa: E501
        :rtype: Thresholds
        """
        return self._thresholds

    @thresholds.setter
    def thresholds(self, thresholds):
        """Sets the thresholds of this PerformanceDataPoint.


        :param thresholds: The thresholds of this PerformanceDataPoint.  # noqa: E501
        :type: Thresholds
        """

        self._thresholds = thresholds

    @property
    def unit(self):
        """Gets the unit of this PerformanceDataPoint.  # noqa: E501


        :return: The unit of this PerformanceDataPoint.  # noqa: E501
        :rtype: str
        """
        return self._unit

    @unit.setter
    def unit(self, unit):
        """Sets the unit of this PerformanceDataPoint.


        :param unit: The unit of this PerformanceDataPoint.  # noqa: E501
        :type: str
        """

        self._unit = unit

    @property
    def value(self):
        """Gets the value of this PerformanceDataPoint.  # noqa: E501


        :return: The value of this PerformanceDataPoint.  # noqa: E501
        :rtype: object
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this PerformanceDataPoint.


        :param value: The value of this PerformanceDataPoint.  # noqa: E501
        :type: object
        """

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PerformanceDataPoint, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PerformanceDataPoint):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PerformanceDataPoint):
            return True

        return self.to_dict() != other.to_dict()
