# coding: utf-8

"""
    Thola

    REST API for Thola.  For more information look at our Github : https://github.com/inexio/thola  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from thola_client.configuration import Configuration


class ServerComponent(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'procs': 'int',
        'users': 'int'
    }

    attribute_map = {
        'procs': 'procs',
        'users': 'users'
    }

    def __init__(self, procs=None, users=None, _configuration=None):  # noqa: E501
        """ServerComponent - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._procs = None
        self._users = None
        self.discriminator = None

        if procs is not None:
            self.procs = procs
        if users is not None:
            self.users = users

    @property
    def procs(self):
        """Gets the procs of this ServerComponent.  # noqa: E501


        :return: The procs of this ServerComponent.  # noqa: E501
        :rtype: int
        """
        return self._procs

    @procs.setter
    def procs(self, procs):
        """Sets the procs of this ServerComponent.


        :param procs: The procs of this ServerComponent.  # noqa: E501
        :type: int
        """

        self._procs = procs

    @property
    def users(self):
        """Gets the users of this ServerComponent.  # noqa: E501


        :return: The users of this ServerComponent.  # noqa: E501
        :rtype: int
        """
        return self._users

    @users.setter
    def users(self, users):
        """Sets the users of this ServerComponent.


        :param users: The users of this ServerComponent.  # noqa: E501
        :type: int
        """

        self._users = users

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ServerComponent, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ServerComponent):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ServerComponent):
            return True

        return self.to_dict() != other.to_dict()
